apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RemoteOperations
  annotations:
    github.com/project-slug: jamesenki/aws-iot-fleetwise-evbatterymonitoring
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: stage
  owner: aws
  providesApis:
    - connected-vehicle-api
---

