@startuml
!include format.iuml
autonumber
!define SDP "SDP\n      Server      "  
!define "ECU"/HU  ""ECU"/HU\n      TU Client      " 
@startuml

skinparam backgroundColor #EEEBDC
skinparam borderThickness 3.5

skinparam sequence {
rectangleBorderThickness 0.5
	 titleBorderRoundCorner 15
 titleBorderThickness 2
 titleBorderColor red
	ParticipantBackgroundColor Orange
	ParticipantBorderColor Orange
	ParticipantFontName Arial
	ParticipantFontSize 17
	ParticipantFontColor black
	LifeLineBorderColor green
	LifeLineBackgroundColor #a5e5d0
	ArrowColor black
}

participant ECU
participant SDP 
participant "Agency Web Application" as AWA
actor "Agent" as Agent 

Agent <-] : Agent Receives Request with Police Report ID /n 
Agent -> AWA: Requests Stolen Vehicle Mode on Vehicle
AWA -> SDP: Posts Call for Stolen Vehicle Mode to SDP
 autonumber
"SDP" --> "SDP": <b>Stolen Vehicle Mode Event \n<b>
"SDP" --> "SDP": Assign MessageId \t\t\t\t\t\t\t\t\t
activate "SDP"
SDP --> "ECU": \t <b><I> Send StolenModeChangeRequest Message \n\t  
note left of ECU: For automatic SVL scenario this can be the first message in the sequence
					
activate "ECU"
"ECU" --> "ECU": <b>Process Message  

"ECU" --> "SDP": <b><I>Send StolenModeChangeResponse Message\n\t
"SDP" --> "SDP": 	<b>Process Message
opt  Stolen Vehicle Assistance Mode ON

loop Stole Vehicle Report - send location every minute
autonumber 7.1
"ECU" --> "SDP": <b><I> Send StolenVehicleReport Message\n\t
"SDP" --> "SDP": <b> Process Message
"SDP" --> "SDP": <b> Assign correlationID
"SDP" --> "ECU": <b> Send  AckMessage
"ECU" --> "ECU": <b> Process AckMessage
end
autonumber 8
"SDP" --> "ECU":<b><I> Send StolenVehicleControlRequest Message \n
"ECU" --> "ECU":<b> Process Message \n
"ECU" --> "SDP":<b><I> Send StolenVehicleControlResponse Message \n
"SDP" --> "SDP": 	<b> Process Message
end

alt Vehicle Recovered
Agent <-]: Agent Learns Vehicle is Recovered or No longer being tracked
Agent -> AWA: end tracking mode
AWW -> SDP: Change Tracking State to Off
SDP -> ECU: End Tracking Mode
create actor "Owner"
SDP -> Owner: Vehicle Recovered
deactivate "ECU"
deactivate SDP


@enduml